config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/', to: 'home#index', as: 'root'
  
  resources :publishers
  
  resources :mangas do
    resources :volumes, param: :number
  end


  get '/profiles/:id', to: 'profiles#show', as: 'profile'
  get '/profiles/:id', to: 'profiles#show', as: 'user'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profiles/:id', to: 'profiles#update'
  delete '/profiles/:id', to: 'profiles#destroy'
  patch '/profiles/ban', to: 'profiles#ban'
  patch '/profiles/unban', to: 'profiles#unban'
  post '/profiles/ban', to: 'profiles#ban'
  post '/profiles/unban', to: 'profiles#unban'

  #routes for admins
  get '/admins', to: 'admins#index', as: 'admins'
  get '/admins/users_list', to: 'admins#users_list', as: 'users_list'
  

  #ajax routes
  post '/change_admin_state', to: 'ajax#change_admin_state'
  post '/change_notifications_state', to: 'ajax#change_notifications_state'
  post '/add_manga_to_list', to: 'ajax#add_manga_to_list'
  post '/remove_manga_from_list', to: 'ajax#remove_manga_from_list'
  post '/notification_read', to: 'ajax#notification_read'
  post '/notification_read_all', to: 'ajax#notification_read_all'
  post '/notification_delete', to: 'ajax#notification_delete'
  post '/notification_delete_read', to: 'ajax#notification_delete_read'
  
end

app/models/manga.rb
class Manga < ApplicationRecord
  belongs_to :release_cycle, required: false
  belongs_to :publisher
  
  has_many :volumes, :dependent => :delete_all
  has_many :manga_lists
  has_many :users, through: :manga_lists

  accepts_nested_attributes_for :release_cycle

  validates :title_japanise, presence: true
  validates :publisher_id, presence: true
  
  def validate_release_cycle!()
    if self.release_cycle.present? && self.release_cycle.correct?
      existingCycle = self.release_cycle.findByAll.first
      
      if existingCycle.blank?
        self.release_cycle.save
        existingCycle = self.release_cycle.findByAll.first
      end
      
      self.release_cycle = existingCycle
    else
      self.release_cycle = nil
    end
  end


  def title_both()
    self.title_polish + (
      self.title_japanise != self.title_polish ? " (" + self.title_japanise + ")" : ""
    )
  end

end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController

before_action :check_admin, only: [:new, :create, :edit, :update, :destroy]
before_action :set_manga, except: [:index, :new, :create]

  def index
    @mangas = Manga.all
  end

  def new
    @manga = Manga.new
    @manga.release_cycle = ReleaseCycle.new
  end

  def create
    @manga = Manga.new(check_params)
    
    @manga.title_polish = @manga.title_japanise if @manga.title_polish.blank?
    @manga.validate_release_cycle!

    if @manga.save
    generate_volumes if params[:generate_volumes].present?

      redirect_to manga_path(@manga)
    else
      render "new"
    end
  end

  def show
  end

  def edit
    @manga.release_cycle = ReleaseCycle.new if @manga.release_cycle.blank?
  end

  def update
    updated_manga = Manga.new(check_params)
    updated_manga.title_polish = updated_manga.title_japanise if updated_manga.title_polish.blank?

    updated_manga.validate_release_cycle!

    if @manga.update(updated_manga.attributes.except("id", "created_at", "updated_at"))
      redirect_to manga_path(@manga)
    else
      render "edit"
    end
  end

  def destroy
    @manga.destroy
    redirect_to mangas_path
  end



  private def check_params()
    params.require(:manga).permit(:id, :title_japanise, :title_polish, :volume_count, :price, :publisher_id, :is_auto_actualized, :is_date_confirmed, release_cycle_attributes: [:number_of_units, :time_unit_id])
  end

  private def set_manga()
    @manga = Manga.find(params[:id])
  end


  private def generate_volumes()
    release_date = params[:start_volume_date]

    (params[:start_volume].to_i..params[:end_volume].to_i).each do |i|
      volume = @manga.volumes.new(
        number: i,
        release_date: release_date,
        is_date_confirmed: i == params[:start_volume].to_i ? true : false,
        is_auto_actualized: @manga.is_auto_actualized
      )
      volume.save

      release_date = volume.expected_date_of_next
    end

    
  end

end

app/helpers/mangas_helper.rb
module MangasHelper
end

app/views/mangas/_form.html.erb
<%= form_for @manga do |f| %>
  <% if @manga.errors.any? %>
    <div id="error_explanation">
      <h2>Wystąpił błąd:</h2>
      
      <ul>
        <% @manga.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr class="list">
      <td>
        <%= f.label :title_japanise, "Tytuł oryginalny" %>
      </td>
      <td>
        <%= f.text_field :title_japanise, class: "normal", required: true %>
      </td>
    </tr>
    <tr class="list">
      <td>
        <%= f.label :title_polish, "Tytuł polski" %>
      </td>
      <td>
        <%= f.text_field :title_polish, class: "normal" %>
      </td>
    </tr>
    <tr class="list">
      <td>
        <%= f.label :publisher_id, "Wydawnictwo" %>
      </td>
      <td>
        <%= f.collection_select :publisher_id, Publisher.all.order(name: :asc), :id, :name, class: "normal", required: true %>
      </td>
    </tr>
    <tr class="list">
      <td>
        <%= f.label :volume_count, "Liczba tomów" %>
      </td>
      <td>
        <%= f.number_field :volume_count, class: "normal" %>
      </td>
    </tr>
    <tr class="list">
      <td>
        <%= label_tag "Cykl wydawniczy" %>
      </td>
      <td style="margin-left: -50px">
        <%= f.fields_for :release_cycle do |ff| %>
          <%= ff.number_field :number_of_units, style: "width: 100px; margin-left: -100px" %>
          </td>
          <td>
            <div style=" margin-left: -100px;">
              <%= ff.collection_select :time_unit_id, TimeUnit.all, :id, :name, style: "width: 100px;" %>
            </div>
        <% end %>
      </td>
    </tr>
    <tr class="list">
      <td>
        <%= f.label :price, "Cena" %>
      </td>
      <td>
        <%= f.number_field :price, step: :any, class: "normal" %>
      </td>
    </tr>
    <tr class="list">
      <td>
        <%= f.label :is_auto_actualized, "Aktualizuj automatycznie" %>
      </td>
      <td>
        <%= f.check_box :is_auto_actualized, class: "normal" %>
      </td>
    </tr>
    <% if @manga.id.blank? %>
      <tr class="list">
        <td>
          <%= label_tag :generate_volumes, "Wygeneruj tomiki" %>
        </td>
        <td>
          <%= check_box_tag :generate_volumes, { checked: false } %>
        </td>
      </tr>
    <% end %>
  </table>
  
  <% if @manga.id.blank? %>
    <div id="volumes_generation" hidden>
      <div id="sub-paragraph">
        <table>
          <tr class="list">
            <td>
              <%= label_tag :start_volume, "Tom początkowy" %>
            </td>
            <td>
              <%= number_field_tag :start_volume %>
            </td>
          </tr>
          <tr class="list">
            <td>
              <%= label_tag :end_volume, "Tom końcowy" %>
            </td>
            <td>
              <%= number_field_tag :end_volume %>
            </td>
          </tr>
          <tr class="list">
            <td>
              <%= label_tag :start_volume_date, "Data tomu początkowego" %>
            </td>
            <td>
              <%= date_field_tag :start_volume_date %>
            </td>
          </tr>
          <tr class="list">
            <td>
              <%= label_tag :is_date_confirmed, "Data pewna" %>
            </td>
            <td>
              <%= check_box_tag :is_date_confirmed %>
            </td>
          </tr>
        </table>
      </div>
    </div>
  <% end %>
  
  <br/>
  <%= f.submit "Zapisz mangę", class: "btn btn-primary" %>
  &nbsp
  <%= link_to "Anuluj", mangas_path, class: "btn btn-primary"%>
<% end %>

 <% if @manga.id.blank? %>
  <script>
    $(function () {
      var $checkbox = $('[id^="generate_volumes"]'),
          $div = $('#volumes_generation'),
          $numberfield_SV = $('[id^="start_volume"]'),
          $numberfield_VC = $('[id^="volume_count"]'),
          $datefield_SVD = $('[id^="start_volume_date"]');

      $checkbox.change(function (e) {
          $div.prop('hidden', !$checkbox.is(':checked'))
          $numberfield_SV.prop('required', $checkbox.is(':checked'))
          $numberfield_VC.prop('required', $checkbox.is(':checked'))
          $datefield_SVD.prop('required', $checkbox.is(':checked'))

      });
    });
  </script>
<% end %>


<style>
  select { width: 100px }
  
  input[type="checkbox"]{
    width: 20px;
    height: 20px;
  }

  td:nth-child(even){
    text-align: center;
    max-width: 500px;
  }

  td:nth-child(even) * {
    text-align: left;
    width: 200px;
  }
</style>

app/views/mangas/edit.html.erb
<h1 class="header">
  Edytuj: <%= @manga.title_polish %>

  <%= link_to(
    manga_path(@manga),
    method: :delete,
    data: { confirm: "Czy jesteś pewien że chcesz usunąć tą mangę i wszystkie jej tomiki?" }
  ) do %>
    <span class="glyphicon glyphicon-trash" style="color: grey; font-size: 30px;"></span>
  <% end %>
</h1>

<div id="sub-paragraph">
  <%= render "form" %>
</div>

app/views/mangas/index.html.erb
<h1 class="header">Wszystkie mangi na stronie:</h1>

<div id="sub-paragraph">

  <table>
    <% @mangas.order(title_polish: :asc).each do |manga| %>
      <tr class="list">
        <td>
          <%= link_to manga.title_polish, manga_path(manga) %>
          <% if admin? %>
            <%= link_to edit_manga_path(manga) do %>
              <span class="glyphicon glyphicon-edit"></span>
            <% end %>            
          <% end %>
        </td>
        
        <% if user_signed_in? %>
          <td style="padding-left: 10px;">
            <%= render partial: "/manga_lists/partials/add_or_remove_button", :locals => { manga: manga } %>
          </td>
        <% end %>

      </tr>
    <% end %>
  </table>

  <% if admin? %>
    <br/>
    <%= link_to "Dodaj", new_manga_path, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/mangas/new.html.erb
<h1 class="header">
  Nowa manga
</h1>

<div id="sub-paragraph">
  <%= render "form" %>
</div>

app/views/mangas/show.html.erb
<h1 class="header">
  <%= @manga.title_polish %>
  <% if admin? %>
    <%= link_to edit_manga_path(@manga) do %>
      <span class="glyphicon glyphicon-edit" style="color: grey;"></span>
    <% end %>
  <% end %>
</h1>

<div id="sub-paragraph">
  <table>
    <tr class="list">
      <td>
        <h4>Tytuł oryginalny: </h4>
      </td>
      <td>
        <%= @manga.title_japanise %><br/>
      </td>
    </tr>
    <tr class="list">
      <td>
        <h4>Cykl wydawniczy: </h4>
      </td>
      <td>
        <% if @manga.release_cycle.present? %>
          Co 
          <%= @manga.release_cycle.number_of_units %>
          <%= @manga.release_cycle.time_unit.name %>
        <% else %>
          Nieokreślony
        <% end %>
      </td>
    </tr>
    <tr class="list">
      <td>
        <h4>Cena: </h4>
      </td>
      <td>
        <% if @manga.price.present? %>
          <%= number_to_currency @manga.price, unit: "zł", format: "%n %u" %>
        <% else %>
          Nieznana
        <% end %>
      </td>
    </tr>
    <tr class="list">
      <td>
        <h4>Liczba tomów: </h4>
      </td>
      <td>
        <%= @manga.volume_count.present? ? @manga.volume_count : "Nieznana" %> (<%= @manga.volumes.count %> w bazie)
      </td>
    </tr>
    <tr class="list">
      <td>
        <h4>Auto aktualizowany? </h4>
      </td>
      <td>
        <%= @manga.is_auto_actualized ? "Tak" : "Nie" %>
      </td>
    </tr>
    
    <% if user_signed_in? %>
      <tr>
        <td></td>
        <td>
          <%= render partial: "/manga_lists/partials/add_or_remove_button", :locals => { manga: @manga } %>
        </td>
      </tr>
    <% end %>
  </table>

  <br/>
  
  <div class="sub-paragraph">
    <h4>Lista tomików:</h4>
    
    <table>
      <% if @manga.volumes.count > 0 %>
        <% @manga.volumes.order(number: :asc).each do |volume| %>
          <tr class="list">
            <td>
              <%= link_to ("Tom " + volume.number.to_s), manga_volume_path(volume.manga, volume) %>
            </td>
            <td>
              <% if volume.release_date.present? %>
                <% unless volume.is_date_confirmed %>ok. <% end %><%= date_format_normal volume.release_date %>
              <% else %>
                Data nieznana
              <% end %>
            </td>
            <td>
            <% if admin? %> 
              <%= link_to edit_manga_volume_path(volume.manga, volume) do %>
                <span class="glyphicon glyphicon-edit"></span>
              <% end %>
            <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr><td></td><td></td><td>Brak<br/></td></tr>
      <% end %>

      <% if admin? %>
        <tr class="list">
          <td></td><td></td>
          <td>
            <%= link_to "Dodaj", new_manga_volume_path(@manga), class: "btn btn-primary" %>
          </td>
        </tr>
      <% end %>
    </table>

    <br/>
    <%= link_to "<< Wróć", mangas_path, class: "btn btn-primary", style: "margin-left: -30px; padding-left: -30px;" %>
  </div>
</div>

<style>
h4{
  font-weight: bolder;
}

td{
  padding-right: 30px;
}
</style>