config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/', to: 'home#index', as: 'root'
  
  resources :publishers
  
  resources :mangas do
    resources :volumes, param: :number
  end


  get '/profiles/:id', to: 'profiles#show', as: 'profile'
  get '/profiles/:id', to: 'profiles#show', as: 'user'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profiles/:id', to: 'profiles#update'
  delete '/profiles/:id', to: 'profiles#destroy'
  patch '/profiles/ban', to: 'profiles#ban'
  patch '/profiles/unban', to: 'profiles#unban'
  post '/profiles/ban', to: 'profiles#ban'
  post '/profiles/unban', to: 'profiles#unban'

  #routes for admins
  get '/admins', to: 'admins#index', as: 'admins'
  get '/admins/users_list', to: 'admins#users_list', as: 'users_list'
  

  #ajax routes
  post '/change_admin_state', to: 'ajax#change_admin_state'
  post '/change_notifications_state', to: 'ajax#change_notifications_state'
  post '/add_manga_to_list', to: 'ajax#add_manga_to_list'
  post '/remove_manga_from_list', to: 'ajax#remove_manga_from_list'
  post '/notification_read', to: 'ajax#notification_read'
  post '/notification_read_all', to: 'ajax#notification_read_all'
  post '/notification_delete', to: 'ajax#notification_delete'
  post '/notification_delete_read', to: 'ajax#notification_delete_read'
  
end

app/views/admins/index.html.erb
<h1 class="header">Panel Administratora</h1>
<br/>

<div id="sub-paragraph">
  <table class="admin">
    <tr>
      <td><%= link_to "Lista mang", mangas_path, class: "btn btn-primary btn-lg btn-block" %></td>
    </tr>
    <tr>
      <td><%= link_to "Dodaj mangę", new_manga_path, class: "btn btn-primary btn-lg btn-block" %></td>
    </tr>
    <tr>
      <td><%= link_to "Lista wydawnictw", publishers_path, class: "btn btn-primary btn-lg btn-block" %></td>
    </tr>
    <tr>
      <td><%= link_to "Dodaj wydawnictwo", new_publisher_path, class: "btn btn-primary btn-lg btn-block" %></td>
    </tr>
    <tr>
      <td><%= link_to "Lista użytkowników", users_list_path, class: "btn btn-primary btn-lg btn-block" %></td>
    </tr>
  </table>
</div>

app/views/admins/users_list.html.erb
<h1 class="header">Lista użytkowników</h1>

<div id="sub-paragraph">
  <table class="bordered">
    <% @users.order(email: :asc).each_with_index do |user, i| %>
      <tr class="list">
        <td class="bordered">
          <h4><%= (i + 1).to_s + ". " %></h4>
        </td>
        <td class="bordered">
          <%= user.email %>
        </td>
        <td class="bordered">
          <%= link_to "Profil", profile_path(user), class: "btn btn-primary" %>
        </td>
        <td class="bordered">
          <%= link_to "Edytuj", edit_profile_path(user), class: "btn btn-primary" %>
        </td>
        <td class="bordered">
          <!-- this: -->
          <button id="btn-admin-g-<%= user.id %>" 
            onclick="change_admin_state( <%= user.id %> )" 
            <% if user.is_admin %>hidden<% end %> >
            Nadaj admina
          </button>
          <!-- or that: -->
          <button id="btn-admin-r-<%= user.id %>" 
            onclick="change_admin_state( <%= user.id %> )" 
            <% if !user.is_admin %>hidden<% end %> >
            Zabierz admina
          </button>
        </td>

        <td class="bordered">
          <% if user.end_of_ban.blank? %>
            <div>
              <%= form_tag "/profiles/ban" do %>
                <%= hidden_field_tag "user_id", user.id %>
                <%= date_field_tag "date", user.end_of_ban, required: true %>
                
                <%= submit_tag "Banuj" %>
              <% end %>
            </div>
          <% else %>
            <div>
              <%= form_tag "/profiles/unban" do %>          
                <%= hidden_field_tag "user_id", user.id %>
                <%= date_field_tag "date", user.end_of_ban, readonly: true %>

                <%= submit_tag "Odblokuj" %>
              <% end %>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to "<< Wróć", admins_path, class: "btn btn-primary" %>


<script>
  function change_admin_state(user_id)
  {
    $.ajax({
      type: "POST",
      url: '/change_admin_state',
      data: { user_id: user_id },
      success: function(response){
        if(response['success']){
          var btnGrant = $("#btn-admin-g-" + user_id);
          var btnRevoke = $("#btn-admin-r-" + user_id);
          if(btnGrant.is(":visible")){
            btnGrant.hide();
            btnRevoke.show();
          }
          else{
            btnGrant.show();
            btnRevoke.hide();
          }
        }
      }
    })
  };
</script>