config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/', to: 'home#index', as: 'root'
  
  resources :publishers
  
  resources :mangas do
    resources :volumes, param: :number
  end


  get '/profiles/:id', to: 'profiles#show', as: 'profile'
  get '/profiles/:id', to: 'profiles#show', as: 'user'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profiles/:id', to: 'profiles#update'
  delete '/profiles/:id', to: 'profiles#destroy'
  patch '/profiles/ban', to: 'profiles#ban'
  patch '/profiles/unban', to: 'profiles#unban'
  post '/profiles/ban', to: 'profiles#ban'
  post '/profiles/unban', to: 'profiles#unban'

  #routes for admins
  get '/admins', to: 'admins#index', as: 'admins'
  get '/admins/users_list', to: 'admins#users_list', as: 'users_list'
  

  #ajax routes
  post '/change_admin_state', to: 'ajax#change_admin_state'
  post '/change_notifications_state', to: 'ajax#change_notifications_state'
  post '/add_manga_to_list', to: 'ajax#add_manga_to_list'
  post '/remove_manga_from_list', to: 'ajax#remove_manga_from_list'
  post '/notification_read', to: 'ajax#notification_read'
  post '/notification_read_all', to: 'ajax#notification_read_all'
  post '/notification_delete', to: 'ajax#notification_delete'
  post '/notification_delete_read', to: 'ajax#notification_delete_read'
  
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :mangas

  validates :name, presence: true

end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController

before_action :check_admin, only: [:new, :create, :edit, :update, :destroy]
before_action :set_publisher, except: [:index, :new, :create]

  def index
    @publishers = Publisher.all
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(check_params)

    if @publisher.save
      redirect_to publisher_path(@publisher)
    else
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @publisher.update(check_params)
      redirect_to publisher_path(@publisher)
    else
      render "edit"
    end
  end

  def destroy
    @publisher.destroy
    redirect_to publishers_path
  end



  private def check_params()
    params.require(:publisher).permit(:id, :name)
  end

  private def set_publisher()
    @publisher = Publisher.find(params[:id])
  end

end

app/helpers/publishers_helper.rb
module PublishersHelper
  def show_manga_title(manga)
    manga.title_polish +
    if manga.title_polish.present? && manga.title_polish != manga.title_japanise
      " (" + manga.title_japanise + ")"
    else
      ""
    end
  end
end

app/views/publishers/_form.html.erb
<%= form_for @publisher do |f| %>
  <% if @publisher.errors.any? %>
    <div id="error_explanation">
      <h2>Wystąpił błąd:</h2>
      
      <ul>
        <% @publisher.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr class="list">
      <td>
        <%= f.label :name, "Nazwa" %>
      </td>
      <td>
        <%= f.text_field :name, style: "text-align: center; margin-left: 40px; width: 175px;", required: true %>
      </td>
    </tr>
    <tr class="list">
      <td></td>
      <td>
      </td>
    </tr>
  </table>

  <br/>
  <%= f.submit "Zapisz", class: "btn btn-primary" %>
  &nbsp
  <%= link_to "Anuluj", publishers_path, class: "btn btn-primary"%>
<% end %>

app/views/publishers/edit.html.erb
<h1 class="header">
  Edytuj: <%= @publisher.name %>

  <%= link_to(
    publisher_path(@publisher),
    method: :delete,
    data: { confirm: "Czy jesteś pewien że chcesz usunąć tego wydawcę i wszystkie jego mangi?" }
  ) do %>
    <span class="glyphicon glyphicon-trash" style="color: grey; font-size: 30px;"></span>
  <% end %>
</h1>

<div id="sub-paragraph">
  <%= render "form" %>
</div>

app/views/publishers/index.html.erb
<h1 class="header">Wszystkie wydawnictwa:</h1>

<div id="sub-paragraph">

  <table>
  <% @publishers.each do |publisher| %>
    <tr class="list" style="font-size: 23px;">
      <td>
        <%= link_to publisher.name, publisher_path(publisher) %>
        <% if admin? %>
          <%= link_to edit_publisher_path(publisher) do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>            
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<% if admin? %>
  <br/>  
  <%= link_to "Dodaj", new_publisher_path, class: "btn btn-primary" %>
<% end %>
</div>

app/views/publishers/new.html.erb
<h1 class="header">
  Nowe wydawnictwo
</h1>

<div id="sub-paragraph">
  <%= render "form" %>
</div>

app/views/publishers/show.html.erb
<h1 class="header">
  Wydawnictwo: 
  <%= @publisher.name %>
  <% if admin? %>
    <%= link_to edit_publisher_path(@publisher) do %>
      <span class="glyphicon glyphicon-edit" style="color: grey;"></span>
    <% end %>
  <% end %>
</h1>

<div id="sub-paragraph">
  <h4 class="header">Mangi: </h4>
  <table>
    <% if @publisher.mangas.present? %>
      <% @publisher.mangas.order(title_polish: :asc).each do |manga| %>
        <tr class="list">
          <td>
            <%= link_to show_manga_title(manga), manga_path(manga) %>
          </td>
        </tr>
      <% end %>
    <% else %>
    <tr><td>Brak</td></tr>
  <% end %>
</table>

<br/>
<%= link_to "<< Wróć", publishers_path, class: "btn btn-primary" %>