config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/', to: 'home#index', as: 'root'
  
  resources :publishers
  
  resources :mangas do
    resources :volumes, param: :number
  end


  get '/profiles/:id', to: 'profiles#show', as: 'profile'
  get '/profiles/:id', to: 'profiles#show', as: 'user'
  get '/profiles/:id/edit', to: 'profiles#edit', as: 'edit_profile'
  patch '/profiles/:id', to: 'profiles#update'
  delete '/profiles/:id', to: 'profiles#destroy'
  patch '/profiles/ban', to: 'profiles#ban'
  patch '/profiles/unban', to: 'profiles#unban'
  post '/profiles/ban', to: 'profiles#ban'
  post '/profiles/unban', to: 'profiles#unban'

  #routes for admins
  get '/admins', to: 'admins#index', as: 'admins'
  get '/admins/users_list', to: 'admins#users_list', as: 'users_list'
  

  #ajax routes
  post '/change_admin_state', to: 'ajax#change_admin_state'
  post '/change_notifications_state', to: 'ajax#change_notifications_state'
  post '/add_manga_to_list', to: 'ajax#add_manga_to_list'
  post '/remove_manga_from_list', to: 'ajax#remove_manga_from_list'
  post '/notification_read', to: 'ajax#notification_read'
  post '/notification_read_all', to: 'ajax#notification_read_all'
  post '/notification_delete', to: 'ajax#notification_delete'
  post '/notification_delete_read', to: 'ajax#notification_delete_read'
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mangowo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: black;">

    <!-- Navbar -->
    <nav class="navbar navbar-inverse" style="height: 50px; width: 100%; position: fixed; top: 0px; z-index: 999;">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to "Mangowo", root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li class="active"><a href="<%= root_url %>"><span class="glyphicon glyphicon-home"></span></a></li>
          <li class="navi"><%= link_to("Mangi", mangas_path) %></li>
          <li class="navi"><%= link_to("Wydawnictwa", publishers_path) %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            
            <li>
              <div class="navbar-link" style="text-align: center; vertical-align: middle; line-height: 50px;">
                Zalogowano jako <strong><%= current_user.username %></strong>
              </div>
            </li>

            <li class="nav-icon-btn nav-icon-btn-success dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <span class="glyphicon glyphicon-bell"/>
                <% if current_user.notifications.notRead.present? %>
                  <div style="margin-top: -10px; margin-left: 9px;">
                    <span class="glyphicon glyphicon-exclamation-sign" style="color: red; font-size: 8px;"></span>
                  </div>
                <% end %>
              </a>
              <%= render "notifications/partials/bar" %>
            </li>
            
            <% if admin? %>
              <li class="navi">
                <%= link_to admins_path do %>
                  Panel admina <span class="glyphicon glyphicon-king"></span>
                <% end %> 
              </li>
            <% end %>

            <li class="navi">
              <%= link_to user_path(current_user), class: 'navbar-link' do %>
                Mój profil <span class="glyphicon glyphicon-user"></span>
              <% end %> 
            </li>
            
            
            <li class="navi">
              <%= link_to edit_user_registration_path, class: 'navbar-link' do %>
                Edytuj profil <span class="glyphicon glyphicon-edit"></span>
              <% end %> 
            </li>
            <li class="navi">
              <%= link_to destroy_user_session_path, method: :delete, class: 'navbar-link' do %>
                Wyloguj <span class="glyphicon glyphicon-off"></span>
              <% end %>
            </li>

            
          <% else %>
            <li class="navi">
              <%= link_to new_user_session_path, class: 'navbar-link' do %>
                Logowanie <span class="glyphicon glyphicon-log-in"></span>
              <% end %>
            </li>
            <li class="navi">
              <%= link_to new_user_registration_path, class: 'navbar-link' do %>
                Rejestracja <span class="glyphicon glyphicon-pencil"></span>
              <% end %> 
            </li>
          <% end %>

        </ul>
      </div>
    </nav>
    <!-- End of navbar -->

    <div class="body" style="margin-top: 50px;">
      <% if notice %>
        <br/>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <br/>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    
      <%= yield %>
    </div>
  </body>
</html>